## script to run models of bird and green up velocities from pheno-mismatch project
## Input: files generated by 1_GetEstimates.R R files:
#         velocityB.rds
#         cellaveB.rds
#         velocityG.rds
#         cellaveG.rds
#         birdgreen.rds

library(tidyverse)
library(lme4)
#library(ggforce)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggplot2)
library(glue)

# import data ----------------------
velB <- read_rds("data/velocityB.rds")
velG <- read_rds("data/velocityG.rds")
bg.mat <- read_rds("data/birdgreen.rds") %>% 
  mutate(vArrMag_log = log(vArrMag),
         vGrMag_log = log(vGrMag))

# VELOCITY --------------------
# Bird speed and Green-up Speed -----------------
(bgs1 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|cell) + (1|species) + (1|year)))
(bgs2 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|cell) + (1|species)))
(bgs3 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|cell) + (1|year)))
(bgs4 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|species) + (1|year)))
(bgs5 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|cell) ))
(bgs6 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|species)))
(bgs7 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|year)))
(bgs8 <-   lm(data = bg.mat, vArrMag_log ~ vGrMag_log))
(bgs9 <- lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + cell_lat + (1|cell)+ (1|species)))
(bgs10 <-lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + cell_lat + (1|cell)+ (1|species) + (1|year)))
(bgs11 <-lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + cell_lat + (1|cell) + (1|species) + (1|year) + AnomLag))
(bgs12 <-lmer(data = bg.mat, vArrMag_log ~ vGrMag_log + (1|cell) + (1|species) + AnomLag))

(taic1 <- AIC(bgs1,bgs2,bgs3,bgs4,bgs5,bgs6,bgs7,bgs8,bgs9,bgs10,bgs11,bgs12) %>% arrange(AIC))  # bgs1 best, but bgs2 is close enough and simpler
sjPlot::tab_model(get(rownames(taic1)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Green-up speed","Latitude", "Lag"),
                  dv.labels= glue("Bird Migration Speed - model {rownames(taic1)[1]}"))

get(rownames(taic1)[1])

# lattice::xyplot(vArrMag_log~vGrMag_log | species,  data=bg.mat, type=c('p','r'), auto.key=F)
lattice::xyplot(fitted(get(rownames(taic1)[1]))~eval(parse(text = paste(names(fixef(get(rownames(taic1)[1])))[-1]))) | species, 
                data=bg.mat, type=c('r'), auto.key=F, cex=0.1,
                par.strip.text=list(cex=0.5), 
                xlab = names(fixef(bgs11))[-1],
                ylab = "vArrMag_log")

plot_model(get(rownames(taic1)[1]), type = "pred", terms = c("vGrMag_log" #"species",
                                                             ))
plot_model(get(rownames(taic1)[1]), type = "pred", terms = c("cell_lat"))
plot_model(get(rownames(taic1)[1]), type = "pred", terms = c("AnomLag"))

# Bird angle and Green up Angle  --------------------
(bga1 <- lmer(data = bg.mat, angB ~ angG + (1|cell) + (1|species) + (1|year)))
(bga2 <- lmer(data = bg.mat, angB ~ angG + (1|cell) + (1|species)))
(bga3 <- lmer(data = bg.mat, angB ~ angG + (1|cell) + (1|year)))
(bga4 <- lmer(data = bg.mat, angB ~ angG + (1|species) + (1|year)))
(bga5 <- lmer(data = bg.mat, angB ~ angG + (1|cell)))
(bga6 <- lmer(data = bg.mat, angB ~ angG + (1|species)))
(bga7 <- lmer(data = bg.mat, angB ~ angG + (1|year)))
(bga8 <- lm(data = bg.mat, angB ~ angG))

(taic2 <- AIC(bga1,bga2,bga3,bga4,bga5,bga6,bga7,bga8,bga9,bga10,bga11,bga12) %>% arrange(AIC))  # bga1 best, but bga2 is close enough and simpler
sjPlot::tab_model(get(rownames(taic2)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Angle"),
                  dv.labels= glue("Bird Migration ANgle - model {rownames(taic2)[1]}"))

# Bird Speed and Latitude ------------------
(bsl1 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|species) + (1|year)))
(bsl1.5<-lmer(data = bg.mat, vArrMag_log ~ cell_lat + I(cell_lat^2) + (1|cell) + (1|species) + (1|year)))
(bsl2 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|species)))
(bsl3 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|year)))
(bsl4 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|species) + (1|year)))
(bsl5 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) ))
(bsl6 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|species)))
(bsl7 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|year)))
(bsl8 <-   lm(data = bg.mat, vArrMag_log ~ cell_lat))

(taic3 <- AIC(bsl1,bsl1.5,bsl2,bsl3,bsl4,bsl5,bsl6,bsl7,bsl8) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic3)[1]),
                   show.re.var= TRUE, 
                   pred.labels =c("Intercept", "Latitude"),
                   dv.labels= glue("Bird Migration Velocity - model {rownames(taic3)[1]}"))

# Green-up Speed and Latitude  --------------------
(gsl1 <- lmer(data = bg.mat, vGrMag_log ~ cell_lat + (1|cell) + (1|year)))
(gsl1.5<-lmer(data = bg.mat, vGrMag_log ~ cell_lat + I(cell_lat^2) + (1|cell) +  (1|year)))
(gsl2 <- lmer(data = bg.mat, vGrMag_log ~ cell_lat + (1|cell)))
(gsl3 <- lmer(data = bg.mat, vGrMag_log ~ cell_lat + (1|year)))
(gsl4 <- lm(data = bg.mat, vGrMag_log ~ cell_lat))

(taic4 <- AIC(gsl1,gsl1.5,gsl2,gsl3,gsl4) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic4)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Latitude"),
                  dv.labels= glue("Green-up speed - model {rownames(taic4)[1]}"))

# ANOMALIES  -----------------------------
# Bird speed with Lag --------------------------
# nothing is significant with log lag
(bsl1 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|cell) + (1|species) + (1|year)))
(bsl2 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|cell) + (1|species)))
(bsl3 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|cell) + (1|year)))
(bsl4 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|species) + (1|year)))
(bsl5 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|cell) ))
(bsl6 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|species)))
(bsl7 <- lmer(data = bg.mat, vArrMag_log ~ lag + (1|year)))
(bsl8 <- lm(data = bg.mat, vArrMag_log ~ lag))
(bsl9 <- lmer(data = bg.mat, vArrMag_log ~ lag + cell_lat + (1|cell)+ (1|species)))

(taic5 <- AIC(bsl1,bsl2,bsl3,bsl4,bsl5,bsl6,bsl7,bsl8,bsl9) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic5)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Lag"),
                  dv.labels= glue("Bird speed - model {rownames(taic5)[1]}"))

ggplot(data = bg.mat, aes(y = vArrMag_log, x = lag)) +
  geom_point() +
  geom_vline(xintercept = 0, color = "red") +
  geom_hline(yintercept = 0, color = "red") +
  facet_wrap_paginate(~species, ncol = 5, nrow = 6, page = 1)
ggplot(data = bg.mat, aes(y = vArrMag, x = lag)) +
  geom_point() +
  geom_vline(xintercept = 0, color = "red") +
  geom_hline(yintercept = 0, color = "red") +
  facet_wrap_paginate(~species, ncol = 5, nrow = 6, page = 2)

# Year and Lags -------------------
(yl1 <- lmer(data = bg.mat, AnomLag ~ year + (1|cell) + (1|species) + (1|year)))
(yl2 <- lmer(data = bg.mat, AnomLag ~ year + (1|cell) + (1|species)))
(yl3 <- lmer(data = bg.mat, AnomLag ~ year + (1|cell) + (1|year)))
(yl4 <- lmer(data = bg.mat, AnomLag ~ year + (1|species) + (1|year)))
(yl5 <- lmer(data = bg.mat, AnomLag ~ year + (1|cell)))
(yl6 <- lmer(data = bg.mat, AnomLag ~ year + (1|species)))
(yl7 <- lmer(data = bg.mat, AnomLag ~ year + (1|year)))

(taic6 <- AIC(yl1,bsl2,bsl3,bsl4,bsl5,bsl6,bsl7,bsl8,bsl9) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic6)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Year"),
                  dv.labels= glue("Lag - model {rownames(taic6)[1]}"))

ggplot(data = bg.mat, aes(x = year, y = AnomLag), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomLag)) +
  geom_hline(yintercept = 0, color = "red") 
ggplot(data = bg.mat, aes(x = year, y = AnomLag), col = "black") +
  geom_smooth(method = "lm", se=TRUE, aes(x = as.integer(year), y = AnomLag))


## which species are late? plot with species ordered in lag
# kid of different results wit log and no log
ggplot(data = bg.mat, 
       aes(x = reorder(species, -AnomLag, FUN = median, na.rm = TRUE), y = AnomLag)) +
  #geom_point() +
  geom_boxplot() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank())

## predictions plots for each model

## maps plots - color of the arrow range of magnitude
  






