## script to run models of bird and green up velocities from pheno-mismatch project
## Input: files generated by 1_GetEstimates.R R files:
#         velocityB.rds
#         cellaveB.rds
#         velocityG.rds
#         cellaveG.rds
#         birdgreen.rds

library(tidyverse)
library(lme4)
library(ggforce)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggplot2)
library(glue)
library(effects)
library(lme4)
library(lemon)
library(RColorBrewer)
library(corrplot)

# full data set
bg.mat <- read_rds("data/birdgreen.rds") %>% 
  mutate(vArrMag_log = log(vArrMag),
         vGrMag_log = log(vGrMag)) %>% 
  rename(cell_lat_s = cell_lat) %>% 
  dplyr::select(-cell_lng)

# only late years
bg.mat <- read_rds("data/birdgreenLATE.rds") %>% 
  mutate(vArrMag_log = log(vArrMag),
         vGrMag_log = log(vGrMag))%>% 
  rename(cell_lat_s = cell_lat) %>% 
  dplyr::select(-cell_lng)

## cell coordinates
cells <- read_rds("data/cellcoor.rds")

bg.mat <- left_join(bg.mat, cells, by="cell")

sps <- "Vireo_olivaceus"  # middle

bg.matX <- bg.mat %>% 
  filter(species == sps) %>% 
  mutate(cell = as.factor(cell),
         AnomVArr = scale(log(vArrMag), scale = FALSE),
         AnomLag = scale(log(lag), scale = FALSE),
         lat_g = ifelse(cell_lat<34, 'low', ifelse(cell_lat > 34 & cell_lat < 42, "mid", ifelse(cell_lat > 42, "high", "opps"))),
         year_g = ifelse(year %in% c(2010,2012), "early", (ifelse(year %in% c(2011,2015,2017), "ave", ifelse(year %in% c(2009,2013,2014,2016), "late", "ops")))))
bg.matX$lat_g <- factor(bg.matX$lat_g, levels = c("low", "mid", "high"))
bg.matX$year_g <- factor(bg.matX$year_g, levels = c("early", "ave", "late"))

bg.matG <- bg.mat %>% 
  dplyr::select(year, cell, cell_lat, cell_lng, gr_mn, gr_ncell,
                NGr, vGrMag, vGrAng, angG, xG, yG, vGrMag_log,
                AnomVGr, AnomDGr, AnomLag) %>% 
  mutate(cell = as.factor(cell),
         lat_g = ifelse(cell_lat<34, 'low', ifelse(cell_lat > 34 & cell_lat < 42, "mid", ifelse(cell_lat > 42, "high", "opps"))), 
         year_g = ifelse(year %in% c(2010,2012), "early", (ifelse(year %in% c(2011,2015,2017), "ave", ifelse(year %in% c(2009,2013,2014,2016), "late", "ops"))))) %>% 
  unique()

bg.matG$lat_g <- factor(bg.matG$lat_g, levels = c("low", "mid", "high")) 
bg.matG$year_g <- factor(bg.matG$year_g, levels = c("early", "ave", "late"))

## plots  
# slide 1 --------------------
ggplot(data = bg.matG, aes(x = year, y = AnomDGr), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomDGr), fill = "darkolivegreen4") +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  ggtitle(glue("Green-up date anomaly"))

# slide 2 -------------------
bg.matX %>% 
  ggplot() +
  geom_boxplot(aes(x = factor(year), y = vGrMag_log, 
                   fill = lat_g)) +
                   #fill = "plum")) +
  geom_hline(yintercept = 0, color = "red")  +
  theme_bw() +
  ggtitle(glue("{bg.matX$species[1]} speed"))

bg.matX %>% 
  ggplot() +
  geom_boxplot(aes(x = factor(year), y = AnomVArr, 
                   fill = lat_g)) +
                   #fill = "plum")) +
  geom_hline(yintercept = 0, color = "red")  +
  theme_bw() +
  ggtitle(glue("{bg.matX$species[1]} speed anomaly")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

## do birds change their speed according to anomalies in green date?

(bsgd1 <-   lm(data = bg.matX, vArrMag_log ~ AnomDGr))
(bsgd2 <- lmer(data = bg.matX, vArrMag_log ~ AnomDGr + (1|year)))
(bsgd3 <-   lm(data = bg.matX, vArrMag_log ~ AnomDGr + cell_lat))
(bsgd4 <- lmer(data = bg.matX, vArrMag_log ~ AnomDGr + (1|year)+ cell_lat))
(bsgd5 <-   lm(data = bg.matX, vArrMag_log ~ cell_lat))
(bsgd6 <- lmer(data = bg.matX, vArrMag_log ~ (1|year)+ cell_lat))
(bsgd7 <- lmer(data = bg.matX, vArrMag_log ~ AnomDGr + (1|year) + lat_g))

head(taic1 <- AIC(bsgd1,bsgd2,bsgd3,bsgd4
                  #,bsgd5,bsgd6
                  ,bsgd7
                  ) %>% arrange(AIC))  # bgs1 best, but bgs2 is close enough and simpler
sjPlot::tab_model(get(rownames(taic1)[1]),
                  show.re.var= TRUE, 
                  #pred.labels =c("Intercept", "Green-up speed","Latitude", "Lag"),
                  #pred.labels =c("Intercept", "Green-up speed"),
                  #dv.labels= glue("Bird Migration Speed - model {rownames(taic1)[1]}",),
                  digits = 3)

rownames(taic1)[1]

plot(Effect(c("AnomDGr"), get(rownames(taic1)[1])))
plot(Effect(c("cell_lat"), get(rownames(taic1)[1])))


(bagd1 <-   lm(data = bg.matX, AnomVArr ~ AnomDGr))
(bagd2 <- lmer(data = bg.matX, AnomVArr ~ AnomDGr + (1|year)))
(bagd3 <-   lm(data = bg.matX, AnomVArr ~ AnomDGr + cell_lat))
(bagd4 <- lmer(data = bg.matX, AnomVArr ~ AnomDGr + (1|year)+ cell_lat))
(bagd5 <-   lm(data = bg.matX, AnomVArr ~ cell_lat))
(bagd6 <- lmer(data = bg.matX, AnomVArr ~ (1|year)+ cell_lat))
(bagd7 <- lmer(data = bg.matX, AnomVArr ~ AnomDGr + (1|year) + lat_g))

head(taic2 <- AIC(bagd1,bagd2,bagd3,bagd4
                  #,bagd5,bagd6
                  ,bagd7
) %>% arrange(AIC))  # bgs1 best, but bgs2 is close enough and simpler
sjPlot::tab_model(get(rownames(taic2)[1]),
                  show.re.var= TRUE, 
                  #pred.labels =c("Intercept", "Green-up speed","Latitude", "Lag"),
                  #pred.labels =c("Intercept", "Green-up speed"),
                  #dv.labels= glue("Bird Migration Speed - model {rownames(taic2)[1]}",),
                  digits = 3)

rownames(taic2)[1]

plot(Effect(c("AnomDGr"), get(rownames(taic2)[1])))
plot(Effect(c("cell_lat"), get(rownames(taic2)[1])))
plot(Effect(c("lat_g"), bagd7))

# slide 3 -------------------
# can I see an average difference between early, mid and late years?
ggplot(data = bg.matG, aes(x = year, y = AnomDGr), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomDGr), fill = "darkolivegreen4") +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  ggtitle(glue("Green-up date anomaly")) +
  facet_rep_wrap(~year_g, ncol = 3, scales='free_x')

bg.matX %>% 
  ggplot() +
  geom_boxplot(aes(x = factor(year), y = vGrMag_log, 
                   fill = lat_g)) +
  #fill = "plum")) +
  geom_hline(yintercept = 0, color = "red")  +
  theme_bw() +
  ggtitle(glue("{bg.matX$species[1]} speed")) +
  facet_rep_wrap(~year_g, ncol = 3, scales='free_x')

bg.matX %>% 
  ggplot() +
  geom_boxplot(aes(x = factor(year), y = AnomVArr, 
                   fill = lat_g)) +
  #fill = "plum")) +
  geom_hline(yintercept = 0, color = "red")  +
  theme_bw() +
  ggtitle(glue("{bg.matX$species[1]} speed anomaly")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_rep_wrap(~year_g, ncol = 3, scales='free_x')

# test for the anomaly between groups
# first just add the model with the year groups as a fixed effect
(bsgd8 <-   lm(data = bg.matX, vArrMag_log ~ AnomDGr + cell_lat + year_g))

head(taic1 <- AIC(bsgd1,bsgd2,bsgd3,bsgd4
                  #,bsgd5,bsgd6
                  ,bsgd7, bsgd8) %>% arrange(AIC)) 

sjPlot::tab_model(bsgd8,
                  show.re.var= TRUE, 
                  digits = 3)

plot(Effect(c("AnomDGr"), get(rownames(taic1)[1])))
plot(Effect(c("cell_lat"), get(rownames(taic1)[1])))

# anom
(bagd8 <- lm(data = bg.matX, AnomVArr ~ AnomDGr + cell_lat + year_g - 1))

head(taic1 <- AIC(bagd1,bagd2,bagd3,bagd4
                  #,bsgd5,bsgd6
                  ,bagd7, bagd8) %>% arrange(AIC)) 

sjPlot::tab_model(bagd8,
                  show.re.var= TRUE, 
                  digits = 3)
names(fixef(bagd8))

plot(Effect(c("AnomDGr"), bagd8))
plot(Effect(c("year_g","cell_lat"), bagd8))

## test to see with mean speed is different between year groups, even though relationship with lat is the same

a <- bg.matX %>% 
  dplyr::select(lat_g,year_g,AnomVArr,cell_lat,vArrMag)
a %>% 
  group_by(year_g) %>% 
  summarize(meanA = mean(AnomVArr, na.rm = TRUE),
            medianA = median(AnomVArr, na.rm = TRUE),
            meanS = mean(vArrMag, na.rm = TRUE),
            medianS = median(vArrMag, na.rm = TRUE))

ggplot(a, aes(x=year_g, y=AnomVArr)) + 
  geom_violin(fill = "plum3", alpha = 0.5) +
  theme_bw() +
  geom_boxplot(width=0.1) +
  geom_hline(yintercept = 0, color = "red") +
  stat_summary(fun.y=mean, geom="point", shape=23, size=2, fill = "blue")
  
year_mean_abs <- lm(AnomVArr ~ year_g + cell_lat, data = a)
sjPlot::tab_model(year_mean_abs,
                  show.re.var= TRUE, 
                  digits = 3)
year_mean_abs <- lm(AnomVArr ~ year_g -1 + cell_lat, data = a)
sjPlot::tab_model(year_mean_abs,
                  show.re.var= TRUE, 
                  digits = 3)

b <- bg.matG %>% 
  dplyr::select(lat_g,year_g,AnomVGr) %>% 
  unique()
ggplot(b, aes(x=year_g, y=AnomVGr)) + 
  geom_violin(fill = "darkolivegreen", alpha = 0.5) +
  theme_bw() +
  geom_boxplot(width=0.1) +
  geom_hline(yintercept = 0, color = "red") +
  stat_summary(fun.y=mean, geom="point", shape=23, size=2, fill = "blue")

# does speed responds to latitude in all years_g
ear <- bg.matX %>% 
  filter(year_g == "early")

year_early_d <- lm(AnomVArr ~ cell_lat + AnomDGr, data = ear)
sjPlot::tab_model(year_early_d,
                  show.re.var= TRUE,
                  dv.labels= glue("Early years bird AnomVArr",),
                  digits = 3)

ave <- bg.matX %>% 
  filter(year_g == "ave")

year_ave_d <- lm(AnomVArr ~ cell_lat + AnomDGr, data = ave)
sjPlot::tab_model(year_ave_d,
                  show.re.var= TRUE, 
                  dv.labels= glue("Average years bird AnomVArr",),
                  digits = 3)

year_late_d <- lm(AnomVArr ~ cell_lat + AnomDGr, data = late)
sjPlot::tab_model(year_late_d,
                  show.re.var= TRUE, 
                  dv.labels= glue("Late years bird AnomVArr",),
                  digits = 3)

# speed
year_early_s <- lm(AnomVArr ~ cell_lat + AnomVGr, data = ear)
sjPlot::tab_model(year_early_s,
                  show.re.var= TRUE,
                  dv.labels= glue("Early years bird AnomVArr",),
                  digits = 3)


year_ave_s <- lm(AnomVArr ~ cell_lat + AnomVGr, data = ave)
sjPlot::tab_model(year_ave_s,
                  show.re.var= TRUE, 
                  dv.labels= glue("Average years bird AnomVArr",),
                  digits = 3)

year_late_s <- lm(AnomVArr ~ cell_lat + AnomVGr, data = late)
sjPlot::tab_model(year_late_s,
                  show.re.var= TRUE, 
                  dv.labels= glue("Late years bird AnomVArr",),
                  digits = 3)

ggplot(data = bg.matX) +
  geom_point(aes(y = AnomVArr, x = cell_lat)) +
  geom_smooth(aes(y = AnomVArr, x = cell_lat), method = "lm") +
  theme_bw() +
  facet_rep_wrap(~year_g, ncol = 3)

# slide 5 ------------------------
ggplot(data = bg.matG, aes(x = year, y = AnomVGr), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomVGr), fill = "darkolivegreen4") +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  ggtitle(glue("Green-up speed anomaly"))


ggplot(data = bg.matG, aes(x = year, y = AnomVGr), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomVGr), fill = "darkolivegreen4") +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  ggtitle(glue("Green-up speed anomaly")) +
  facet_rep_wrap(~year_g, ncol = 3, scales='free_x')

gsyg <- lm(data = bg.matG, AnomVGr ~ year_g )
sjPlot::tab_model(gsyg,
                  show.re.var= TRUE, 
                  digits = 3)

ggplot(data = bg.matG, aes(x = year_g, y = AnomVGr), col = "black") +
  #geom_point() +
  #geom_boxplot(aes(x = factor(year_g), y = AnomVGr), fill = "darkolivegreen4") +
  geom_violin(fill = "darkolivegreen", alpha = 0.5) +
  geom_boxplot(width=0.1) +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  ggtitle(glue("Green-up speed anomaly"))

gsyg2 <- lm(data = bg.matG, AnomVGr ~ year_g - 1)
sjPlot::tab_model(gsyg2,
                  show.re.var= TRUE, 
                  digits = 3)

gslyg <- lm(data = bg.matG, AnomVGr ~ cell_lat + year_g + cell_lat * year_g)
sjPlot::tab_model(gslyg,
                  show.re.var= TRUE, 
                  digits = 3)

plot(Effect(c("year_g","cell_lat"), gslyg))


gslyb <- lm(data = bg.matX, AnomVArr ~ cell_lat + year_g + cell_lat * year_g)
sjPlot::tab_model(gslyb,
                  show.re.var= TRUE, 
                  digits = 3)

plot(Effect(c("year_g","cell_lat"), gslyb))

bg.matX %>% 
  #mutate(AnomVArr = scale(vArrMag)) %>% 
  ggplot() +
  geom_point(aes(y = lag, x = cell_lat, col = as.factor(year))) +
  #scale_colour_gradient2(low = "red", high = "blue", mid = 'green', na.value = NA) +  #geom_boxplot(aes(x = cell_lat, y = vArrMag_log)) +
  geom_hline(yintercept = 0, color = "black")  +
  #ylim(c(-1,1000)) +
  theme_bw() +
  #ggtitle(glue("{bg.matX$species[1]} lag")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_rep_wrap(~year_g, ncol = 3, repeat.tick.labels = T) + 
  geom_smooth(aes(y = lag, x = cell_lat), col = "black", se = F)

bg.matX %>% 
  group_by(year_g) %>% 
  summarize(meanL = mean(lag, na.rm = TRUE),
            medianL = median(lag, na.rm = TRUE),
            meanLa = mean(AnomLag, na.rm = TRUE),
            medianLa = median(AnomLag, na.rm = TRUE))

bg.matX %>% 
  ggplot() +
  geom_point(aes(y = AnomVArr, x = cell_lat, col = as.factor(year))) +
  geom_hline(yintercept = 0, color = "black")  +
  theme_bw() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_rep_wrap(~year_g, ncol = 3, repeat.tick.labels = T) + 
  geom_smooth(aes(y = AnomVArr, x = cell_lat), col = "plum", se = F) +
  geom_smooth(aes(y = AnomVGr, x = cell_lat), col = "darkolivegreen", se = F)

ggplot(data = bg.matG, aes(x = cell_lat, y = AnomVGr), col = "black") +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  ggtitle(glue("Green-up speed anomaly")) +
  facet_rep_wrap(~year_g, ncol = 3)

myPalette <- colorRampPalette(brewer.pal(11, "PRGn"))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(-30,40))

bg.matX %>% 
  ggplot() +
  geom_point(aes(x = AnomVGr, y = AnomVArr, col = lag)) +
  geom_hline(yintercept = 0, color = "red")  +
  geom_vline(xintercept = 0, color = "red")  +
  theme_bw() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_wrap(~year_g, ncol = 3) + sc 
#geom_abline(intercept = 0, slope = 1, size = 0.5)
#geom_smooth(aes(x = AnomDGr, y = AnomDArr, col = cell_lat), method = "lm")

corrplot(M, method="circle")




















ggplot(bg.matG) +
  geom_point(aes(x = cell_lat, y = AnomVGr)) +
  #geom_boxplot(aes(x = factor(year), y = AnomVArr)) +
  geom_hline(yintercept = 0, color = "red")  +
  #ylim(c(-1,2)) +
  theme_bw() +
  ggtitle(glue("green up speed anomaly")) +
  facet_wrap(~year)

(gal1 <- lmer(data = bg.matG, AnomVGr ~ cell_lat + (1|cell) + (1|year)))
(gal2 <- lmer(data = bg.matG, AnomVGr ~ cell_lat + (1|year)))
(gal3 <- lmer(data = bg.matG, AnomVGr ~ cell_lat + (1|cell)))
(gal4 <- lmer(data = bg.matG, AnomVGr ~ cell_lat + I(cell_lat^2) +(1|cell) + (1|year)))
(gal5 <- lmer(data = bg.matG, AnomVGr ~ cell_lat + I(cell_lat^2) +(1|year)))
(gal6 <- lmer(data = bg.matG, AnomVGr ~ cell_lat + I(cell_lat^2) +(1|cell)))
(gal7 <- lmer(data = bg.matG, abs(AnomVGr) ~ cell_lat + (1|cell) + (1|year)))
(gal8 <- lmer(data = bg.matG, abs(AnomVGr) ~ cell_lat + (1|year)))
(gal9 <- lmer(data = bg.matG, abs(AnomVGr) ~ cell_lat + (1|cell)))
(gal10 <- lmer(data = bg.matG, abs(AnomVGr) ~ cell_lat + (1|cell) + (1|year) + I(cell_lat^2)))
(gal11 <- lmer(data = bg.matG, abs(AnomVGr) ~ cell_lat + (1|year) + I(cell_lat^2)))
(gal12 <- lmer(data = bg.matG, abs(AnomVGr) ~ cell_lat + (1|cell) + I(cell_lat^2)))

(taig1 <- AIC(gal1,gal2,gal3,gal4,gal5,gal6,gal7,gal8,gal9,gal10,gal11,gal12) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taig1)[1]),
                  show.re.var= TRUE, 
                  #pred.labels =c("Intercept", "Latitude", "Lag"),
                  #dv.labels= glue("Bird Migration speed anomaly - model {rownames(taig1)[1]}"),
                  digits = 3)


(gsl1 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + (1|cell) + (1|year)))
(gsl2 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + (1|year)))
(gsl3 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + (1|cell)))
(gsl4 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + I(cell_lat^2) +(1|cell) + (1|year)))
(gsl5 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + I(cell_lat^2) +(1|year)))
(gsl6 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + I(cell_lat^2) +(1|cell)))
(gsl7 <- lmer(data = bg.matG, abs(vGrMag_log) ~ cell_lat + (1|cell) + (1|year)))
(gsl8 <- lmer(data = bg.matG, abs(vGrMag_log) ~ cell_lat + (1|year)))
(gsl9 <- lmer(data = bg.matG, abs(vGrMag_log) ~ cell_lat + (1|cell)))
(gsl10 <- lmer(data = bg.matG, abs(vGrMag_log) ~ cell_lat + (1|cell) + (1|year) + I(cell_lat^2)))
(gsl11 <- lmer(data = bg.matG, abs(vGrMag_log) ~ cell_lat + (1|year) + I(cell_lat^2)))
(gsl12 <- lmer(data = bg.matG, abs(vGrMag_log) ~ cell_lat + (1|cell) + I(cell_lat^2)))

(taig2 <- AIC(gsl1,gsl2,gsl3,gsl4,gsl5,gsl6,gsl7,gsl8,gsl9,gsl10,gsl11,gsl12) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taig2)[1]),
                  show.re.var= TRUE, 
                  #pred.labels =c("Intercept", "Latitude", "Lag"),
                  digits = 3)
  
  
  
bg.mat %>% 
dplyr::select(year, cell, cell_lat, cell_lng, gr_mn, gr_ncell,
              NGr, vGrMag, vGrAng, angG, xG, yG, vGrMag_log,
              AnomVGr, AnomDGr, AnomLag) %>% 
unique() %>% 
#filter(year == 2017) %>% 
#mutate(AnomVArr = scale(vArrMag)) %>% 
ggplot() +
geom_point(aes(x = cell_lat, y = AnomDGr)) +
#geom_boxplot(aes(x = factor(year), y = AnomVArr)) +
geom_hline(yintercept = 0, color = "red")  +
#ylim(c(-1,2)) +
theme_bw() +
facet_wrap(~year)


## bird! -------------

myPalette <- colorRampPalette(brewer.pal(11, "PuRd"))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(-30,30))



bg.matX %>% 
  filter(year %in% c(2009,2012)) %>% 
  #mutate(AnomVArr = scale(vArrMag)) %>% 
  ggplot() +
  geom_point(aes(y = AnomVGr, x = cell_lat), col = "darkolivegreen") +
  geom_point(aes(y = AnomVArr, x = cell_lat), col = "deeppink") +
  #scale_colour_gradient2(low = "red", high = "blue", mid = 'green', na.value = NA) +  #geom_boxplot(aes(x = cell_lat, y = vArrMag_log)) +
  geom_hline(yintercept = 0, color = "black")  +
  #ylim(c(-1,1000)) +
  theme_bw() +
  #ggtitle(glue("{bg.matX$species[1]} lag")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_rep_wrap(~year, ncol = 1, repeat.tick.labels = T) + #sc +
  #geom_abline(intercept = 0, slope = 1, size = 0.5)
  geom_smooth(aes(y = AnomVGr, x = cell_lat), col = "darkolivegreen", se = F) +
  geom_smooth(aes(y = AnomVArr, x = cell_lat), col = "deeppink", se = F) +
  geom_smooth(aes(y = AnomLag, x = cell_lat), col = "orange", se = F)

# can green up vary more than birds can? :(

bg.matX %>% select(year, vArrMag_log, vGrMag_log) %>%
  pivot_longer(., cols = c(vArrMag_log, vGrMag_log), 
               names_to = "Var", values_to = "Val") %>%
  mutate(Var2 = ifelse(Var == 'vArrMag_log', '2_vArrMag_log', '1_vGrMag_log')) %>% 
  ggplot(aes(x = as.factor(year), y = Val, fill = Var2)) +
  geom_boxplot() + theme_bw()

bg.matX %>% select(year, vArrMag_log, vGrMag_log) %>%
  pivot_longer(., cols = c(vArrMag_log, vGrMag_log), 
               names_to = "Var", values_to = "Val") %>%
  mutate(Var2 = ifelse(Var == 'vArrMag_log', '2_vArrMag_log', '1_vGrMag_log')) %>% 
  ggplot(aes(x = year, y = Val, fill = Var2)) +
  geom_boxplot() + theme_bw()

bg.matX %>% select(year, AnomVArr, AnomVGr) %>%
  pivot_longer(., cols = c(AnomVGr, AnomVArr), 
               names_to = "Var", values_to = "Val") %>%
  mutate(Var2 = ifelse(Var == 'AnomVArr', '2_AnomVArr', '1_AnomVGr')) %>% 
  ggplot(aes(x = as.factor(year), y = Val, fill = Var2)) +
  geom_boxplot() + theme_bw()

bg.matX %>% select(year, AnomVArr, AnomVGr) %>%
  pivot_longer(., cols = c(AnomVArr, AnomVGr), 
               names_to = "Var", values_to = "Val") %>%
  mutate(Var2 = ifelse(Var == 'AnomVArr', '2_AnomVArr', '1_AnomVGr')) %>% 
  ggplot(aes(x = year, y = Val, fill = Var2)) +
  geom_boxplot() + theme_bw()
 

bg.matX %>% 
  filter(year %in% c(2009,2012)) %>% 
  #mutate(AnomVArr = scale(vArrMag)) %>% 
  ggplot() +
  geom_point(aes(y = lag, x = cell_lat), col = "orange") +
  #scale_colour_gradient2(low = "red", high = "blue", mid = 'green', na.value = NA) +  #geom_boxplot(aes(x = cell_lat, y = vArrMag_log)) +
  geom_hline(yintercept = 0, color = "black")  +
  #ylim(c(-1,1000)) +
  theme_bw() +
  #ggtitle(glue("{bg.matX$species[1]} lag")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_rep_wrap(~year, ncol = 1, repeat.tick.labels = T) + 
  geom_smooth(aes(y = lag, x = cell_lat), col = "orange", se = F)

bg.matX %>% 
  filter(year %in% c(2009,2012)) %>% 
  #mutate(AnomVArr = scale(vArrMag)) %>% 
  ggplot() +
  geom_point(aes(y = lag, x = cell_lat), col = "orange") +
  #scale_colour_gradient2(low = "red", high = "blue", mid = 'green', na.value = NA) +  #geom_boxplot(aes(x = cell_lat, y = vArrMag_log)) +
  geom_hline(yintercept = 0, color = "black")  +
  #ylim(c(-1,1000)) +
  theme_bw() +
  #ggtitle(glue("{bg.matX$species[1]} lag")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_rep_wrap(~year, ncol = 1, repeat.tick.labels = T) + 
  geom_smooth(aes(y = lag, x = cell_lat), col = "orange", se = F)

bg.matX %>% 
  #filter(year %in% c(2009,2012)) %>% 
  #mutate(AnomVArr = scale(vArrMag)) %>% 
  ggplot() +
  geom_boxplot(aes(y = lag, x = as.factor(year)), col = "orange") +
  #scale_colour_gradient2(low = "red", high = "blue", mid = 'green', na.value = NA) +  #geom_boxplot(aes(x = cell_lat, y = vArrMag_log)) +
  geom_hline(yintercept = 0, color = "black")  
  
bg.matX %>% 
  #filter(year %in% c(2009,2012)) %>% 
  #mutate(AnomVArr = scale(vArrMag)) %>% 
  ggplot() +
  geom_boxplot(aes(y = vArrMag_log, x = as.factor(year))) 




