## script to run models of bird and green up velocities from pheno-mismatch project
## Input: files generated by 1_GetEstimates.R R files:
#         velocityB.rds
#         cellaveB.rds
#         velocityG.rds
#         cellaveG.rds
#         birdgreen.rds

library(tidyverse)
library(lme4)
library(ggforce)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggplot2)
library(glue)
library(effects)

# import data ----------------------
velB <- read_rds("data/velocityB.rds")
velG <- read_rds("data/velocityG.rds")

# full data set
bg.mat <- read_rds("data/birdgreen.rds") %>% 
  mutate(vArrMag_log = log(vArrMag),
         vGrMag_log = log(vGrMag))
# only late years
bg.mat <- read_rds("data/birdgreenLATE.rds") %>% 
  mutate(vArrMag_log = log(vArrMag),
         vGrMag_log = log(vGrMag))

# VELOCITY --------------------
# Bird speed and Green-up Speed -----------------
# only latitude is significant - faster north
(bgs1 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|cell) + (1|species) + (1|year)))
(bgs2 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|cell) + (1|species)))
(bgs3 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|cell) + (1|year)))
(bgs4 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|species) + (1|year)))
(bgs5 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|cell) ))
(bgs6 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|species)))
(bgs7 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|year)))
(bgs8 <-   lm(data = bg.matX, vArrMag_log ~ vGrMag_log))
(bgs9 <- lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + cell_lat + (1|cell)+ (1|species)))
(bgs10 <-lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + cell_lat + (1|cell)+ (1|species) + (1|year)))
(bgs11 <-lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + cell_lat + (1|cell) + (1|species) + (1|year) + AnomLag))
(bgs12 <-lmer(data = bg.matX, vArrMag_log ~ vGrMag_log + (1|cell) + (1|species) + AnomLag))

head(taic1 <- AIC(bgs1,bgs2,bgs3,bgs4,bgs5,bgs6,bgs7,bgs8,bgs9,bgs10,bgs11,bgs12) %>% arrange(AIC))  # bgs1 best, but bgs2 is close enough and simpler
sjPlot::tab_model(get(rownames(taic1)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Green-up speed","Latitude", "Lag"),
                  dv.labels= glue("Bird Migration Speed - model {rownames(taic1)[1]}",),
                  digits = 3)

get(rownames(taic1)[1])

# lattice::xyplot(vArrMag_log~vGrMag_log | species,  data=bg.mat, type=c('p','r'), auto.key=F)
lattice::xyplot(fitted(get(rownames(taic1)[1]))~eval(parse(text = paste(names(fixef(get(rownames(taic1)[1])))[-1]))) | species, 
                data=bg.mat, type=c('r'), auto.key=F, cex=0.1,
                par.strip.text=list(cex=0.5), 
                xlab = names(fixef(get(rownames(taic1)[1])))[-1],
                ylab = "vArrMag_log")

plot(Effect(c("vGrMag_log"), get(rownames(taic1)[1])))
plot(Effect(c("cell_lat"), get(rownames(taic1)[1])))
plot(Effect(c("AnomLag"), get(rownames(taic1)[1])))

# Bird angle and Green up Angle  --------------------
# nothing significant
(bga1 <- lmer(data = bg.mat, angB ~ angG + (1|cell) + (1|species) + (1|year)))
(bga2 <- lmer(data = bg.mat, angB ~ angG + (1|cell) + (1|species)))
(bga3 <- lmer(data = bg.mat, angB ~ angG + (1|cell) + (1|year)))
(bga4 <- lmer(data = bg.mat, angB ~ angG + (1|species) + (1|year)))
(bga5 <- lmer(data = bg.mat, angB ~ angG + (1|cell)))
(bga6 <- lmer(data = bg.mat, angB ~ angG + (1|species)))
(bga7 <- lmer(data = bg.mat, angB ~ angG + (1|year)))
(bga8 <- lm(data = bg.mat, angB ~ angG))

(taic2 <- AIC(bga1,bga2,bga3,bga4,bga5,bga6,bga7,bga8) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic2)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Angle"),
                  dv.labels= glue("Bird Migration Angle - model {rownames(taic2)[1]}"),
                  digits = 3)
rownames(taic2)[1]

lattice::xyplot(fitted(get(rownames(taic2)[1]))~eval(parse(text = 
                                                             paste(names(fixef(get(rownames(taic2)[1])))[-1]))) | species, 
                data=bg.mat, type=c('r'), auto.key=F, cex=0.1,
                par.strip.text=list(cex=0.5), 
                xlab = names(fixef(get(rownames(taic2)[1])))[-1],
                ylab = "angB")

# Bird Speed and Latitude ------------------
# latitude is significant - faster north
(bsl1 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|species) + (1|year)))
(bsl1.5<-lmer(data = bg.mat, vArrMag_log ~ cell_lat + I(cell_lat^2) + (1|cell) + (1|species) + (1|year)))
(bsl2 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|species)))
(bsl3 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|year)))
(bsl4 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|species) + (1|year)))
(bsl5 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) ))
(bsl6 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|species)))
(bsl7 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|year)))
(bsl8 <-   lm(data = bg.mat, vArrMag_log ~ cell_lat))
(bsl9 <- lmer(data = bg.mat, vArrMag_log ~ cell_lat + (1|cell) + (1|species) + (1|year) + AnomLag))

(taic3 <- AIC(bsl1,bsl1.5,bsl2,bsl3,bsl4,bsl5,bsl6,bsl7,bsl8, bsl9) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic3)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Latitude", "Lag"),
                  dv.labels= glue("Bird Migration Velocity - model {rownames(taic3)[1]}"),
                  digits = 3)

rownames(taic3)[1]

lattice::xyplot(fitted(get(rownames(taic3)[1]))~eval(parse(text = 
                                                             paste(names(fixef(get(rownames(taic3)[1])))[-1]))) | species, 
                data=bg.mat, type=c('r'), auto.key=F, cex=0.1,
                par.strip.text=list(cex=0.5), 
                xlab = names(fixef(get(rownames(taic3)[1])))[-1],
                ylab = "vArrMag_log")

plot(Effect(c("cell_lat"), get(rownames(taic3)[1])))
plot(Effect(c("AnomLag"), get(rownames(taic3)[1])))

# Green-up Speed and Latitude  --------------------
bg.matG <- bg.mat %>% 
  dplyr::select(year, cell, cell_lat, cell_lng, gr_mn, gr_ncell,
                NGr, vGrMag, vGrAng, angG, xG, yG, vGrMag_log) %>% 
  unique()

(gsl1 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + (1|cell) + (1|year)))
(gsl1.5<-lmer(data = bg.matG, vGrMag_log ~ cell_lat + I(cell_lat^2) + (1|cell) +  (1|year)))
(gsl2 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + (1|cell)))
(gsl3 <- lmer(data = bg.matG, vGrMag_log ~ cell_lat + (1|year)))
(gsl4 <- lm(data = bg.matG, vGrMag_log ~ cell_lat))

(taic4 <- AIC(gsl1,gsl1.5,gsl2,gsl3,gsl4) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic4)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Latitude"),
                  dv.labels= glue("Green-up speed - model {rownames(taic4)[1]}"),
                  digits = 3)

# Year and Green-up speed -------------------
(yg1 <- lmer(data = bg.mat, AnomVGr ~ year + (1|cell) + (1|species)))
(yg2 <- lmer(data = bg.mat, AnomVGr ~ year + (1|cell)))
(yg3 <- lmer(data = bg.mat, AnomVGr ~ year + (1|species)))
(yg4  <-  lm(data = bg.mat, AnomVGr ~ year))
(yg5  <-  lm(data = bg.mat, AnomVGr ~ as.factor(year)))

(taic6 <- AIC(yg1,yg2,yg3,yg4,yg5) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic6)[1]),
                  show.re.var= TRUE, 
                  pred.labels = as.character(seq(2009,2017,1)),
                  dv.labels= glue("Lag - model {rownames(taic6)[1]}"),
                  digits = 3)

ggplot(data = bg.mat, aes(x = year, y = AnomVGr), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomVGr)) +
  geom_hline(yintercept = 0, color = "red") 

# ANOMALIES  -----------------------------
# Bird speed with Lag --------------------------
# nothing is significant with log lag
(bsl1 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|cell) + (1|species) + (1|year)))
(bsl2 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|cell) + (1|species)))
(bsl3 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|cell) + (1|year)))
(bsl4 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|species) + (1|year)))
(bsl5 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|cell) ))
(bsl6 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|species)))
(bsl7 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + (1|year)))
(bsl8 <- lm(data = bg.mat, AnomVArr ~ AnomDGr))
(bsl9 <- lmer(data = bg.mat, AnomVArr ~ AnomDGr + cell_lat + (1|cell)+ (1|species)))

(taic5 <- AIC(bsl1,bsl2,bsl3,bsl4,bsl5,bsl6,bsl7,bsl8,bsl9) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic5)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Lag"),
                  dv.labels= glue("Bird speed - model {rownames(taic5)[1]}"),
                  digits = 3)

rownames(taic5)[1]

plot(Effect(c("lag"), get(rownames(taic5)[1])))

lattice::xyplot(fitted(get(rownames(taic5)[1]))~eval(parse(text = 
                                                             paste(names(fixef(get(rownames(taic5)[1])))[-1]))) | species, 
                data=bg.mat, type=c('r'), auto.key=F, cex=0.1,
                par.strip.text=list(cex=0.5), 
                xlab = names(fixef(get(rownames(taic5)[1])))[-1],
                ylab = "vArrMag_log")


## which species are late? plot with species ordered in lag - most species are arriving earlier
# kind of different results wit log and no log
ggplot(data = bg.mat, 
       aes(x = reorder(species, -AnomLag, FUN = median, na.rm = TRUE), y = AnomLag)) +
  #geom_point() +
  geom_boxplot() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank())

# Year and Lags -------------------
(yl1 <- lmer(data = bg.mat, AnomLag ~ year + (1|cell) + (1|species)))
(yl2 <- lmer(data = bg.mat, AnomLag ~ year + (1|cell)))
(yl3 <- lmer(data = bg.mat, AnomLag ~ year + (1|species)))
(yl4  <-  lm(data = bg.mat, AnomLag ~ year))
(yl5  <-  lm(data = bg.mat, AnomLag ~ as.factor(year)))

(taic7 <- AIC(yl1,yl2,yl3,yl4,yl5) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic7)[1]),
                  show.re.var= TRUE, 
                  pred.labels = as.character(seq(2009,2017,1)),
                  dv.labels= glue("Lag - model {rownames(taic7)[1]}"),
                  digits = 3)

ggplot(data = bg.mat, aes(x = year, y = AnomLag), col = "black") +
  #geom_point() +
  geom_boxplot(aes(x = factor(year), y = AnomLag)) +
  geom_hline(yintercept = 0, color = "red") 

# Lag varying according to arrival date --------------------------
# nothing is significant with log lag
(ld1 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|cell) + (1|species) + (1|year)))
(ld2 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|cell) + (1|species)))
(ld3 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|cell) + (1|year)))
(ld4 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|species) + (1|year)))
(ld5 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|cell) ))
(ld6 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|species)))
(ld7 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + (1|year)))
(ld8 <- lm(data = bg.mat, lag ~ arr_GAM_mean))
(ld9 <- lmer(data = bg.mat, lag ~ arr_GAM_mean + cell_lat + (1|cell)+ (1|species)))

(taic8 <- AIC(ld1,ld2,ld3,ld4,ld5,ld6,ld7,ld8,ld9) %>% arrange(AIC))  
sjPlot::tab_model(get(rownames(taic8)[1]),
                  show.re.var= TRUE, 
                  pred.labels =c("Intercept", "Lag"),
                  dv.labels= glue("Bird speed - model {rownames(taic8)[1]}"),
                  digits = 3)

rownames(taic8)[1]

plot(Effect(paste(names(fixef(get(rownames(taic8)[1])))[-1]), get(rownames(taic8)[1])))

lattice::xyplot(fitted(get(rownames(taic8)[1]))~eval(parse(text = 
                                                             paste(names(fixef(get(rownames(taic8)[1])))[-1]))) | species, 
                data=bg.mat, type=c('r'), auto.key=F, cex=0.1,
                par.strip.text=list(cex=0.5), 
                xlab = names(fixef(get(rownames(taic8)[1])))[-1],
                ylab = "lag")
## which species are late? plot with species ordered in lag
# kind of different results wit log and no log
ggplot(data = bg.mat, 
       aes(x = reorder(species, -lag, FUN = median, na.rm = TRUE), y = lag)) +
  #geom_point() +
  geom_boxplot() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank())

ggplot(data = bg.matX, 
       aes(y = AnomVArr, x = AnomVGr)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  geom_smooth()

ggplot(data = bg.mat, 
       aes(x = arr_GAM_mean, y = lag)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw() +
  geom_smooth(method = "lm")

ggplot(data = bg.mat, 
       aes(y = arr_GAM_mean, x = as.factor(cell_lat))) +
  geom_boxplot() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw()
